services:
  app:
    build: .
    # command: node --inspect=0.0.0.0:9229 index.js
    # command: npx nodemon --inspect=0.0.0.0:9229 index.ts
    command: node --require ts-node/register -r tsconfig-paths/register --inspect=0.0.0.0:9229 index.ts
    ports:
      - 8081:8081
      - 9229:9229